### ISSUE TITLE
Issue with bonding (active-backup mode)

### ISSUE THREAD

**Issue by svallala** [intel/bond-cni#11] opened 2020-04-30 23:36 UTC
I am deploying 25 pods with bonded SRIOV VFs, in active-backup mode. At least one of the pods goes into a state, where the Pod is not receiving any traffic from other Pods deployed on the same physical node.

The issue is seen only when the following things happen:
- Instead of eth1, eth2 becomes the active interface
- Bond0 MAC address is set to eth1 MAC address

**[root@test1-pktgen-22 /]# ip addr**
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if598: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1480 qdisc noqueue state UP group default
    link/ether f2:cb:cf:b2:3e:6d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.21.20.97/32 scope global eth0
       valid_lft forever preferred_lft forever
5: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether fa:41:ef:aa:5e:4c brd ff:ff:ff:ff:ff:ff
    inet 192.168.60.124/24 scope global bond0
       valid_lft forever preferred_lft forever
23: eth1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond0 state UP group default qlen 1000
    link/ether fa:41:ef:aa:5e:4c brd ff:ff:ff:ff:ff:ff
151: eth2: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond0 state UP group default qlen 1000
    link/ether fa:41:ef:aa:5e:4c brd ff:ff:ff:ff:ff:ff

**[root@test1-pktgen-22 /]# cat /proc/net/bonding/bond0**
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

Bonding Mode: fault-tolerance (active-backup)
Primary Slave: None
Currently Active Slave: eth2
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 0
Down Delay (ms): 0

Slave Interface: eth1
MII Status: up
Speed: 10000 Mbps
Duplex: full
Link Failure Count: 1
Permanent HW addr: fa:41:ef:aa:5e:4c
Slave queue ID: 0

Slave Interface: eth2
MII Status: up
Speed: 10000 Mbps
Duplex: full
Link Failure Count: 1
Permanent HW addr: a2:98:78:e0:01:4e
Slave queue ID: 0

**[root@cscale-82-73 ~]# echo "$out" | egrep "test1-pktgen-22|test1-pktgen-18|test1-pktgen-21"**
test1-pktgen-18   2/2     Running   0          10m   192.168.60.105   qct-03   <none>           <none>
test1-pktgen-21   2/2     Running   0          10m   192.168.60.142   qct-05   <none>           <none>
test1-pktgen-22   2/2     Running   0          10m   192.168.60.124    qct-05   <none>           <none>

Issue in action
---------------
Pod with issue - test1-pktgen-22 on Host qct-05

**Ping to Pod on the same host fails**
[root@test1-pktgen-22 /]# ping 192.168.60.142
PING 192.168.60.142 (192.168.60.142) 56(84) bytes of data.
From 192.168.60.124 icmp_seq=1 Destination Host Unreachable

**Ping to Pod on a different host works fine**
[root@test1-pktgen-22 /]# ping 192.168.60.105
PING 192.168.60.105 (192.168.60.105) 56(84) bytes of data.
64 bytes from 192.168.60.105: icmp_seq=1 ttl=64 time=0.150 ms

If I bring down the eth2 interface, which changes the primary slave for the bond0 to eth1, then everything works fine

[root@test1-pktgen-22 /]# ip link set down dev eth2
[root@test1-pktgen-22 /]# ip link set up dev eth2
[root@test1-pktgen-22 /]# ping 192.168.60.142
PING 192.168.60.142 (192.168.60.142) 56(84) bytes of data.
64 bytes from 192.168.60.142: icmp_seq=1 ttl=64 time=0.275 ms

If I disable eth1 and enable it again, the primary slave of the bond0 interface would have changed to eth2 and then things don't work again

[root@test1-pktgen-22 /]# ip link set down dev eth1
[root@test1-pktgen-22 /]# ip link set up dev eth1
[root@test1-pktgen-22 /]# ping 192.168.60.142
PING 192.168.60.142 (192.168.60.142) 56(84) bytes of data.

For "active-backup" mode, as far as I know, there is no need for any upstream switch configuration since the switch would only see one MAC address which is picked by the Bond interface. Seems like something is not getting set up properly.

**Network Attachments**

[root@cscale-82-73 ~]# kubectl get net-attach-def -n t001-u000003 test1-pktgen-22-bond0  test1-pktgen-22-net1-0 test1-pktgen-22-net1-1 -o yaml
apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    creationTimestamp: "2020-04-30T22:28:34Z"
    generation: 1
    name: test1-pktgen-22-bond0
    namespace: t001-u000003
    resourceVersion: "370830"
    selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/t001-u000003/network-attachment-definitions/test1-pktgen-22-bond0
    uid: 9ae2acf9-e2bd-4eb2-af0d-c02d93e4729d
  spec:
    config: '{ "cniVersion": "0.3.1", "name": "bond-net", "plugins": [ { "type": "bond",
      "mode": "active-backup", "linksInContainer": true, "miimon": "100", "links":
      [{"name": "eth1"}, {"name": "eth2"}], "ipam": { "type": "robin-ipam" } }, {
      "type": "tuning", "mtu": 9000, "sysctl": { "net.ipv6.conf.all.accept_ra": "0",
      "net.ipv6.conf.default.accept_ra": "0", "net.ipv6.conf.bond0.accept_ra": "0"
      } } ] }'
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/resourceName: intel.com/enp59s0f0_iavf
    creationTimestamp: "2020-04-30T22:28:26Z"
    generation: 1
    name: test1-pktgen-22-net1-0
    namespace: t001-u000003
    resourceVersion: "370733"
    selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/t001-u000003/network-attachment-definitions/test1-pktgen-22-net1-0
    uid: cb21d2cd-4c5f-4e2d-80b2-64c0932cf87e
  spec:
    config: '{ "cniVersion": "0.3.1", "name": "sriov-network", "plugins": [ { "vlan":
      20, "spoofchk": "off", "type": "sriov" }, { "type": "tuning", "mtu": 9000, "sysctl":
      { "net.ipv6.conf.all.accept_ra": "0", "net.ipv6.conf.default.accept_ra": "0",
      "net.ipv6.conf.eth1.accept_ra": "0" } } ] }'
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/resourceName: intel.com/enp59s0f1_iavf
    creationTimestamp: "2020-04-30T22:28:31Z"
    generation: 1
    name: test1-pktgen-22-net1-1
    namespace: t001-u000003
    resourceVersion: "370784"
    selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/t001-u000003/network-attachment-definitions/test1-pktgen-22-net1-1
    uid: a95b01f2-ea5f-4d37-b4af-5f60de85a050
  spec:
    config: '{ "cniVersion": "0.3.1", "name": "sriov-network", "plugins": [ { "vlan":
      20, "spoofchk": "off", "type": "sriov" }, { "type": "tuning", "mtu": 9000, "sysctl":
      { "net.ipv6.conf.all.accept_ra": "0", "net.ipv6.conf.default.accept_ra": "0",
      "net.ipv6.conf.eth2.accept_ra": "0" } } ] }'
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

Multus: v3.4.1
Kubernetes: 1.16.3
SRIOV: Latest Version
Bond CNI: Latest Version

**Comment by killianmuldoon** [comment] 2020-05-01 13:27
Is there any logs output to dmesg when this happens? Also - since this is repeatedly coming up - is this always related to the same PF or the same VF ? Are all of the VFs configured the same? 

Is VF trust set to on? I don't see that in the sriov-cni spec you've posted here.

**Comment by svallala** [comment] 2020-05-01 19:22
Yes, trust is not set. I read that only spoofchk should be turned off for bonding to work. I have seen this across different nodes and PFs. I am able to reproduce this issue consistently even with a couple of pods.

All the bond interfaces created set the effective MAC to that of the port eth1 and the active slave is eth1. When I deployed 50 pods, some of them have the eth2 as the active slave. All such pods have issues.

I don't see any obvious errors reported in the dmesg. To reproduce the issue, I just brought eth1/eth2 up and down a couple of times and then I can't ping. Can only ping, if I brought one of the interfaces down.

[root@qct-03 ~]# dmesg -w
[41309.736343] nf_conntrack: falling back to vmalloc.
[41309.739458] nf_conntrack: falling back to vmalloc.
[41309.758780] nf_conntrack: falling back to vmalloc.
[41309.763097] nf_conntrack: falling back to vmalloc.
[41310.925618] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[41310.927515] IPv6: ADDRCONF(NETDEV_UP): cali69bcf3d944e: link is not ready
[41310.927531] IPv6: ADDRCONF(NETDEV_CHANGE): cali69bcf3d944e: link becomes ready
[41310.927951] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[41310.985869] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[41311.007250] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[41311.073085] i40e 0000:3b:00.0: Setting VLAN 20, QOS 0x0 on VF 59
[41311.135219] IPv6: ADDRCONF(NETDEV_UP): eth1: link is not ready
[41311.141854] i40e 0000:3b:00.0: Setting VLAN 20, QOS 0x0 on VF 44
[41311.183813] IPv6: ADDRCONF(NETDEV_UP): eth1: link is not ready
[41311.194453] iavf 0000:3b:09.3 eth1: NIC Link is Up Speed is 10 Gbps Full Duplex
[41311.195223] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
[41311.199527] i40e 0000:3b:00.1: Setting VLAN 20, QOS 0x0 on VF 58
[41311.206330] i40e 0000:3b:00.1: Setting VLAN 20, QOS 0x0 on VF 63
[41311.243514] iavf 0000:3b:07.4 eth1: NIC Link is Up Speed is 10 Gbps Full Duplex
[41311.261647] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
[41311.287132] IPv6: ADDRCONF(NETDEV_UP): eth2: link is not ready
[41311.301801] IPv6: ADDRCONF(NETDEV_UP): eth2: link is not ready
[41311.313353] iavf 0000:3b:11.7 eth2: changing MTU from 1500 to 9000
[41311.382013] iavf 0000:3b:09.3 eth1: changing MTU from 9000 to 1500
[41311.406510] iavf 0000:3b:11.2 eth2: NIC Link is Up Speed is 10 Gbps Full Duplex
[41311.476015] iavf 0000:3b:11.7 eth2: NIC Link is Up Speed is 10 Gbps Full Duplex
[41311.494989] iavf 0000:3b:09.3 eth1: NIC Link is Up Speed is 10 Gbps Full Duplex
[41311.496173] bond0: Enslaving eth1 as a backup interface with a down link
[41311.497772] IPv6: ADDRCONF(NETDEV_CHANGE): eth2: link becomes ready
[41311.568483] iavf 0000:3b:11.2 eth2: changing MTU from 9000 to 1500
[41311.682072] iavf 0000:3b:11.2 eth2: NIC Link is Up Speed is 10 Gbps Full Duplex
[41311.683144] bond0: Enslaving eth2 as a backup interface with a down link
[41311.743772] IPv6: ADDRCONF(NETDEV_CHANGE): eth2: link becomes ready
[41311.747372] iavf 0000:3b:07.4 eth1: changing MTU from 9000 to 1500
[41311.861138] iavf 0000:3b:07.4 eth1: NIC Link is Up Speed is 10 Gbps Full Duplex
[41311.862475] bond0: Enslaving eth1 as a backup interface with a down link
[41311.924068] iavf 0000:3b:11.7 eth2: changing MTU from 9000 to 1500
[41312.037933] iavf 0000:3b:11.7 eth2: NIC Link is Up Speed is 10 Gbps Full Duplex
[41312.038826] bond0: Enslaving eth2 as a backup interface with a down link
[41312.303531] IPv6: ADDRCONF(NETDEV_UP): bond0: link is not ready
[41312.314580] iavf 0000:3b:09.3 eth1: changing MTU from 1500 to 9000
[41312.315090] iavf 0000:3b:11.2 eth2: changing MTU from 1500 to 9000
[41312.333539] bond0: link status definitely up for interface eth1, 10000 Mbps full duplex
[41312.333547] bond0: making interface eth1 the new active one
[41312.334118] bond0: first active interface up!
[41312.334485] bond0: link status definitely up for interface eth2, 10000 Mbps full duplex
[41312.334558] IPv6: ADDRCONF(NETDEV_CHANGE): bond0: link becomes ready
[41312.431295] iavf 0000:3b:09.3 eth1: NIC Link is Up Speed is 10 Gbps Full Duplex
[41312.431348] iavf 0000:3b:11.2 eth2: NIC Link is Up Speed is 10 Gbps Full Duplex
[41312.434610] bond0: link status definitely down for interface eth1, disabling it
[41312.434622] bond0: now running without any active interface!
[41312.434845] bond0: link status definitely down for interface eth2, disabling it
[41312.562576] bond0: link status definitely up for interface eth1, 10000 Mbps full duplex
[41312.562584] bond0: making interface eth1 the new active one
[41312.563295] bond0: first active interface up!
[41312.563591] bond0: link status definitely up for interface eth2, 10000 Mbps full duplex
[41312.600694] IPv6: ADDRCONF(NETDEV_UP): bond0: link is not ready
[41312.602509] bond0: link status definitely up for interface eth1, 10000 Mbps full duplex
[41312.602516] bond0: making interface eth1 the new active one
[41312.603020] bond0: first active interface up!
[41312.603371] bond0: link status definitely up for interface eth2, 10000 Mbps full duplex
[41312.603667] IPv6: ADDRCONF(NETDEV_CHANGE): bond0: link becomes ready
[41312.609301] iavf 0000:3b:07.4 eth1: changing MTU from 1500 to 9000
[41312.609814] iavf 0000:3b:11.7 eth2: changing MTU from 1500 to 9000
[41312.725944] iavf 0000:3b:11.7 eth2: NIC Link is Up Speed is 10 Gbps Full Duplex
[41312.725996] iavf 0000:3b:07.4 eth1: NIC Link is Up Speed is 10 Gbps Full Duplex
[41312.803789] bond0: link status definitely down for interface eth1, disabling it
[41312.803806] bond0: now running without any active interface!
[41312.804086] bond0: link status definitely down for interface eth2, disabling it
[41312.903499] bond0: link status definitely up for interface eth1, 10000 Mbps full duplex
[41312.903507] bond0: making interface eth1 the new active one
[41312.904015] bond0: first active interface up!
[41312.904347] bond0: link status definitely up for interface eth2, 10000 Mbps full duplex
[41786.216958] i40e 0000:3b:00.0 enp59s0f0: NIC Link is Down
[41786.223141] iavf 0000:3b:07.4 eth1: NIC Link is Down
[41786.224719] iavf 0000:3b:09.3 eth1: NIC Link is Down
[41786.252830] bond0: link status definitely down for interface eth1, disabling it
[41786.252839] bond0: making interface eth2 the new active one
[41786.288836] bond0: link status definitely down for interface eth1, disabling it
[41786.288845] bond0: making interface eth2 the new active one
[41836.921209] i40e 0000:3b:00.0 enp59s0f0: NIC Link is Up, 10 Gbps Full Duplex, Flow Control: None
[41836.925907] iavf 0000:3b:07.4 eth1: NIC Link is Up Speed is 10 Gbps Full Duplex
[41836.927486] iavf 0000:3b:09.3 eth1: NIC Link is Up Speed is 10 Gbps Full Duplex
[41836.966335] bond0: link status definitely up for interface eth1, 10000 Mbps full duplex
[41836.987309] bond0: link status definitely up for interface eth1, 10000 Mbps full duplex
[41884.364178] bond0: link status definitely down for interface eth1, disabling it
[41886.664251] bond0: link status definitely down for interface eth2, disabling it
[41886.664266] bond0: now running without any active interface!
[41889.903723] iavf 0000:3b:09.3 eth1: NIC Link is Up Speed is 10 Gbps Full Duplex
[41889.974789] bond0: link status definitely up for interface eth1, 10000 Mbps full duplex
[41889.974797] bond0: making interface eth1 the new active one
[41889.975299] bond0: first active interface up!
[

**Comment by krishnajs** [comment] 2020-05-07 21:29
@svallala on the switch can you change the MTU within the Jumbo frame range i.e. between 1000 bytes to 1500 bytes and let us know if the issue happens. What is the MTU of the NIC - PF and the related VFs set to ?

**Comment by svallala** [comment] 2020-05-08 02:05
We have tried 9000 and 1500 and hitting the same issue. VFs are set to the default 1500.

**Comment by krishnajs** [comment] 2020-05-11 13:26
@svallala we don't have Switch to reproduce this issue can you please see if you can reproduce this issue with connecting to another host rather than switch.

**Comment by killianmuldoon** [comment] 2020-05-12 14:56
@svallala could you look at the solution posted in #14 and see if that solves your problem? The solution leverages PR #15  which adds the failOverMac option in the bond network attachment definition.

**Comment by svallala** [comment] 2020-05-12 20:15
@killianmuldoon took your fix and it works well. Thanks

**Comment by killianmuldoon** [comment] 2020-05-13 06:45
@svallala - glad to hear it. Hopefully this change will be merged in in the next few days.

**Closed** 2020-05-28 12:48 UTC
